source 'https://rubygems.org'

gem 'jekyll', github: 'jekyll/jekyll'

group :jekyll_plugins do
  gem 'jekyll-feed', github: 'jekyll/jekyll-feed'
  gem 'jekyll-seo-tag', github: 'jekyll/jekyll-seo-tag'
  gem 'jekyll-sitemap', github: 'jekyll/jekyll-sitemap'
  gem 'tzinfo'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
  gem 'wdm', '>= 0.1.0' if Gem.win_platform?
end
